=== joergdeutschmann-i7/proto2testbed/controller/assets/config.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "config.schema.json",
    "title": "Proto-Testbed Config",
    "description": "Testbed config for a Proto-Testbed setup package",
    "type": "object",
    "properties": {
        "settings": {
            "type": "object",
            "properties": {
                "management_network": {
                    "type": "string"
                },
                "diskimage_basepath": {
                    "type": "string"
                },
                "startup_init_timeout": {
                    "type": "number"
                },
                "experiment_timeout": {
                    "type": "number"
                }
            },
            "additionalItems": false
        },
        "networks": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "host_ports": {
                        "type": "array",
                        "items": {
                            "type": [
                                "string",
                                "null"
                            ]
                        }
                    }
                },
                "additionalItems": false,
                "required": [
                    "name",
                    "host_ports"
                ]
            }
        },
        "integrations": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "mode": {
                        "type": "string",
                        "enum": [
                            "await",
                            "startstop",
                            "ns3-emulation"
                        ]
                    },
                    "environment": {
                        "type": [
                            "object",
                            "null"
                        ]
                    },
                    "invoke_after": {
                        "type": "string",
                        "enum": [
                            "startup",
                            "network",
                            "init"
                        ]
                    },
                    "wait_after_invoke": {
                        "type": "number"
                    }
                },
                "additionalItems": false,
                "required": [
                    "name",
                    "mode",
                    "settings"
                ],
                "allOf": [
                    {
                        "if": {
                            "properties": {
                                "mode": {
                                    "const": "await"
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "settings": {
                                    "type": "object",
                                    "properties": {
                                        "start_script": {
                                            "type": "string"
                                        },
                                        "wait_for_exit": {
                                            "type": "number"
                                        },
                                        "start_delay": {
                                            "type": "number"
                                        }
                                    },
                                    "required": [
                                        "start_script",
                                        "wait_for_exit"
                                    ],
                                    "additionalItems": false
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "mode": {
                                    "const": "startstop"
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "settings": {
                                    "type": "object",
                                    "properties": {
                                        "start_script": {
                                            "type": "string"
                                        },
                                        "stop_script": {
                                            "type": "string"
                                        },
                                        "wait_for_exit": {
                                            "type": "number"
                                        },
                                        "start_delay": {
                                            "type": "number"
                                        }
                                    },
                                    "required": [
                                        "start_script",
                                        "stop_script"
                                    ],
                                    "additionalItems": false
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "mode": {
                                    "const": "ns3-emulation"
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "settings": {
                                    "type": "object",
                                    "properties": {
                                        "basepath": {
                                            "type": "string"
                                        },
                                        "program": {
                                            "type": "string"
                                        },
                                        "interfaces": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        },
                                        "wait": {
                                            "type": "boolean"
                                        },
                                        "fail_on_exist": {
                                            "type": "boolean"
                                        },
                                        "args": {
                                            "type": [
                                                "object",
                                                "null"
                                            ]
                                        }
                                    },
                                    "required": [
                                        "basepath",
                                        "program",
                                        "interfaces"
                                    ],
                                    "additionalItems": false
                                }
                            }
                        }
                    }
                ]
            }
        },
        "instances": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "diskimage": {
                        "type": "string"
                    },
                    "setup_script": {
                        "type": [
                            "string",
                            "null"
                        ]
                    },
                    "environment": {
                        "type": [
                            "object",
                            "null"
                        ]
                    },
                    "cores": {
                        "type": "number"
                    },
                    "memory": {
                        "type": "number"
                    },
                    "netmodel": {
                        "type": "string",
                        "enum": [
                            "virtio",
                            "e1000",
                            "rtl8139"
                        ]
                    },
                    "networks": {
                        "oneOf": [
                            {
                                "type": "null"
                            },
                            {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        ]
                    },
                    "preserve_files": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "applications": {
                        "type": [
                            "array",
                            "null"
                        ],
                        "items": {
                            "type": "object",
                            "properties": {
                                "application": {
                                    "type": "string"
                                },
                                "name": {
                                    "type": "string"
                                },
                                "delay": {
                                    "type": "number"
                                },
                                "runtime": {
                                    "type": "number"
                                },
                                "dont_store": {
                                    "type": "boolean"
                                },
                                "settings": {
                                    "type": "object"
                                }
                            },
                            "required": [
                                "application",
                                "name",
                                "runtime",
                                "settings"
                            ],
                            "additionalItems": false
                        }
                    }
                },
                "additionalItems": false,
                "required": [
                    "name",
                    "diskimage",
                    "setup_script",
                    "environment",
                    "networks",
                    "applications"
                ]
            }
        }
    },
    "required": [
        "settings",
        "networks",
        "integrations",
        "instances"
    ],
    "additionalItems": false
}

=== joergdeutschmann-i7/proto2testbed/setups/example1/testbed.json
{
    "settings": {
        "machines_internet_access": true,
        "management_network": "172.16.99.0/24",
        "diskimage_basepath": "/tmp"
    },
    "networks": [
        {
            "name": "exp0",
            "host_ports": []
        },
        {
            "name": "exp1",
            "host_ports": []
        }
    ],
    "integrations": [],
    "instances": [
        {
            "name": "endpoint-a",
            "diskimage": "{{IMAGE_ENDPOINT}}",
            "setup_script": "endpoint/setup.sh",
            "environment": {
                "IP_ADDRESS": "10.0.1.1/24",
                "ROUTE": "10.0.2.0/24 via 10.0.1.2",
                "WIREGUARD": "{{WIREGUARD_A}}"
            },
            "cores": 2,
            "memory": 1024,
            "networks": [
                "exp0"
            ],
            "applications": [
                {
                    "application": "iperf3-server",
                    "name": "a-iperf-server",
                    "delay": 0,
                    "runtime": 100,
                    "settings": {}
                },
                {
                    "application": "procmon",
                    "name": "a-procmon",
                    "delay": 5,
                    "runtime": 60,
                    "settings": {
                        "interfaces": ["enp0s3"],
                        "system": false
                    }
                }
            ]
        },
        {
            "name": "router",
            "diskimage": "{{IMAGE_ROUTER}}",
            "setup_script": "router/setup.sh",
            "environment": {
                "IP_ADDRESS_0": "10.0.1.2/24",
                "IP_ADDRESS_1": "10.0.2.2/24"
            },
            "cores": 2,
            "memory": 1024,
            "networks": [
                "exp0",
                "exp1"
            ],
            "applications": [
                {
                    "application": "run-program",
                    "name": "add_delay",
                    "delay": 30,
                    "runtime": 60,
                    "settings": {
                        "command": "/tmp/application.sh",
                        "ignore_timeout": true,
                        "environment": {
                            "INTERFACE": "enp0s3",
                            "DELAY_MS": 100
                        }
                    }
                }
            ]
        },
        {
            "name": "endpoint-b",
            "diskimage": "{{IMAGE_ENDPOINT}}",
            "setup_script": "endpoint/setup.sh",
            "environment": {
                "IP_ADDRESS": "10.0.2.1/24",
                "ROUTE": "10.0.1.0/24 via 10.0.2.2",
                "WIREGUARD": "{{WIREGUARD_B}}"
            },
            "cores": 2,
            "memory": 1024,
            "networks": [
                "exp1"
            ],
            "applications": [
                {
                    "application": "iperf3-client",
                    "name": "b-iperf-client",
                    "delay": 1,
                    "runtime": 60,
                    "settings": {
                        "host": "{{IPERF_HOST}}"
                    }
                },
                {
                    "application": "ping",
                    "name": "b-ping",
                    "delay": 10,
                    "runtime": 60,
                    "settings": {
                        "target": "{{PING_TARGET}}",
                        "source": "{{PING_SOURCE}}"
                    }
                }
            ]
        }
    ]
}

=== joergdeutschmann-i7/proto2testbed/setups/example2/testbed.json
{
    "settings": {
        "machines_internet_access": true,
        "management_network": "172.16.99.0/24",
        "diskimage_basepath": "/tmp"
    },
    "networks": [
        {
            "name": "exp0",
            "host_ports": [
                "ns3_em0"
            ]
        },
        {
            "name": "exp1",
            "host_ports": [
                "ns3_em1"
            ]
        }
    ],
    "integrations": [
        {
            "mode": "await",
            "name": "run-ns3",
            "invoke_after": "startup",
            "wait_after_invoke": 3,
            "settings": {
                "start_script": "integration.sh",
                "wait_for_exit": 110
            },
            "environment": {
                "ROUTERS": "{{ROUTERS}}"
            }
        }
    ],
    "instances": [
        {
            "name": "endpoint-a",
            "diskimage": "endpoint.qcow2",
            "setup_script": "endpoint/setup.sh",
            "environment": {
                "IP_ADDRESS": "172.20.0.2/24",
                "ROUTE": "172.20.{{ROUTERS}}.0/24 via 172.20.0.1"
            },
            "cores": 2,
            "memory": 1024,
            "networks": [
                "exp0"
            ],
            "applications": [
                {
                    "application": "iperf3-server",
                    "name": "a-iperf-server",
                    "delay": 0,
                    "runtime": 100,
                    "settings": {}
                }
            ]
        },
        {
            "name": "endpoint-b",
            "diskimage": "endpoint.qcow2",
            "setup_script": "endpoint/setup.sh",
            "environment": {
                "IP_ADDRESS": "172.20.{{ROUTERS}}.2/24",
                "ROUTE": "172.20.0.0/24 via 172.20.{{ROUTERS}}.1"
            },
            "cores": 2,
            "memory": 1024,
            "networks": [
                "exp1"
            ],
            "applications": [
                {
                    "application": "iperf3-client",
                    "name": "b-iperf-client",
                    "delay": 5,
                    "runtime": 60,
                    "settings": {
                        "host": "172.20.0.2"
                    }
                },
                {
                    "application": "ping",
                    "name": "b-ping",
                    "delay": 0,
                    "runtime": 65,
                    "settings": {
                        "target": "172.20.0.2"
                    }
                }
            ]
        }
    ]
}
